# Generated by Django 5.2.4 on 2025-07-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='melissa', max_length=50),
        ),
    ]
